### PR TITLE
Fix LowPower Sleep Mode

### PR DESCRIPTION
**Pull request by ABOSTM**
Fix LowPower Sleep Mode:

* fix: restore Main regulator on LowPower Sleep exit
* fix: in case of LowPower Sleep, it is necessary to decrease CPU Frequency 

Fixes https://github.com/stm32duino/STM32LowPower/issues/73

### CODE REVIEW

**Comment by ABOSTM** [comment]
Currently tested only on L4.
Waiting CI on other STM32 series

**Comment by tshcherban** [comment]
@ABOSTM can verify on STM32L051C8T6
can you give some details what should i check?

**Comment by ABOSTM** [comment]
Tested on all STM32 series, with ExternalWakeup example,
working fine.

**Review by fpistm — APPROVED** [review]
LGTM

**Pull request merged**
